name: Mirzosharif
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme #
title: Mirzosharif Habibov
description: Everything about me
show_downloads: true
google_analytics: G-YWTFZNX169
