name: Mirzosharif
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme #
title: Mirzosharif Habibov
description: Just a 16 y.o. dev from Fergana, Uzbekistan
show_downloads: true
google_analytics: G-YWTFZNX169
codeforces: https://codeforces.com/profile/-MxM
